name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Publish @rmc-toolkit/core
        run: npm publish --workspace packages/core

      - name: Publish @rmc-toolkit/vite
        run: npm publish --workspace packages/vite

      - name: Publish @rmc-toolkit/react
        run: npm publish --workspace packages/react

      - name: Publish @rmc-toolkit/vue
        run: npm publish --workspace packages/vue
